<template>
  <!-- <div>
    <a href="https://hyypeonline.com/2017/09/26/jessachalla/" target="_blank">
      <img
        src="https://hyypeonline.com/2017/09/26/jessachalla/"
        height="50"
        width="50"
    /></a>
    <a href="https://www.wgvunews.org/post/web-directory-launches-help-kent-county-residents-find-food-distribution-sites" target="_blank">
      <img
        src="https://www.wgvunews.org/post/web-directory-launches-help-kent-county-residents-find-food-distribution-sites"
        height="50"
        width="50"
    /></a>

    <iframe
      height="400px"
      width="800px"
      src="https://hyypeonline.com/2017/09/26/jessachalla/"
    ></iframe>
    <iframe
      height="400px"
      width="800px"
      src="https://www.wgvunews.org/post/web-directory-launches-help-kent-county-residents-find-food-distribution-sites"
    ></iframe>
    <iframe
      height="400px"
      width="800px"
      src="https://www.schoolnewsnetwork.org/2013/12/26/dual-enrolled-northview-artist-seeks-move-others/"
    ></iframe>
    <iframe
      height="400px"
      width="800px"
      src="https://www.mlive.com/entertainment/grand-rapids/2012/08/uicas_artworks_program_unveils.html"
    ></iframe>
    <iframe
      height="400px"
      width="800px"
      src="https://www.youtube.com/watch?v=ak5wA4oTAdM"
    ></iframe>
    <iframe
      height="400px"
      width="800px"
      src="https://goindocal.com/whole-again-may-erlewine"
    ></iframe>
    <iframe
      height="400px"
      width="800px"
      src="https://www.youtube.com/watch?v=Ay7RBRSID2Q&t=2s"
    ></iframe>
    <iframe
      height="400px"
      width="800px"
      src="https://www.wzzm13.com/article/tech/girls-learning-computer-coding-has-support-in-west-michigan/69-9c79f448-385b-4e7a-8454-893dbefaabda"
    ></iframe>
    <iframe
      height="400px"
      width="800px"
      src="https://vimeo.com/278569064?fbclid=IwAR1FWsxLy1oLYBG-hZ96XtUKwuita3x35kY7FcOn_LXCASGgrNZMoYSgiGU"
    ></iframe>
    <iframe
      height="400px"
      width="800px"
      src="https://www.youtube.com/watch?v=ENcT8qFkf9E"
    ></iframe>
  </div> -->
</template>
